import HomeProgressCard from "@/components/home-progress-card";
import Link from "@/components/safe-link";
import { PortalHeader, PrototypeFooter } from "@/components/portal-header";
import { MobileBottomNav } from "@/components/mobile-bottom-nav";
import { Reveal } from "@/components/motion/reveal";
import { RevealText } from "@/components/motion/reveal-text";
import { Accessibility,ArrowRight,CalendarDays,Car,CheckCircle2,FileCheck2,Gavel,Languages,MapPin,ShieldCheck,Workflow } from "lucide-react";

const services=[
  {icon:FileCheck2,title:"Learner Licence",copy:"Check eligibility, documents, fee and time before you begin.",meta:"About 8 minutes",href:"/apply/learner-licence",action:"View application"},
  {icon:CalendarDays,title:"Appointments",copy:"Book or manage a clearly labelled demo RTO visit.",meta:"Choose a time",href:"/appointments",action:"Manage visit"},
  {icon:Workflow,title:"Track application",copy:"See what is complete and the exact action that comes next.",meta:"Live demo status",href:"/track",action:"Track now"},
  {icon:Car,title:"Vehicle details",copy:"Check a seeded synthetic vehicle record safely.",meta:"Demo record",href:"/vehicles",action:"Check vehicle"},
  {icon:Gavel,title:"eChallan",copy:"Review and test-pay a fictional demonstration challan.",meta:"No real payment",href:"/challans",action:"Check challan"},
];

function ProcessIllustration(){return <svg className="process-illustration" viewBox="0 0 640 132" fill="none" aria-hidden="true" focusable="false"><path d="M92 66H278M362 66H548" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeDasharray="6 9"/><path d="m270 56 12 10-12 10m82-20 12 10-12 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><g fill="#fff" stroke="currentColor" strokeWidth="3"><circle cx="66" cy="66" r="29"/><circle cx="320" cy="66" r="29"/><circle cx="574" cy="66" r="29"/></g><path d="M56 67h20M66 57v20M305 64h30M314 52h12v24M562 55h23v17h-23zM566 76h15" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export default function Home(){return <><PortalHeader/><main className="home-page pb-20 md:pb-0">
  <section className="home-hero"><div className="wrap home-hero-grid"><div className="home-hero-copy"><p className="eyebrow">Public-service prototype</p><RevealText text="RTO services, made easier to understand."/><p className="lede">Simple guided forms, saved progress, clear instructions and multilingual support—designed around the citizen, not the system.</p><div className="hero-actions"><Link className="button primary" href="/services">Start a service <ArrowRight/></Link><Link className="button secondary" href="/track">Track application</Link></div><div className="hero-assurance"><ShieldCheck/><div><strong>Safe demonstration</strong><p className="m-0 text-sm text-slate-500">No real Aadhaar, government records or payments are used.</p></div></div></div><Reveal delay={.12} direction="right"><HomeProgressCard/></Reveal></div></section>
  <section className="home-section wrap" id="popular-services"><Reveal><div className="section-heading"><div><p className="eyebrow">Popular services</p><h2>Start with what you need</h2><p>Each service explains the process in plain language before asking for information.</p></div><Link className="text-link" href="/services">View all services <ArrowRight/></Link></div></Reveal><div className="popular-service-grid">{services.map(({icon:Icon,...service},index)=><Reveal delay={index*.06} key={service.title}><Link href={service.href} className="modern-service-card"><span className="service-icon"><Icon/></span><div><h3>{service.title}</h3><p>{service.copy}</p></div><small>{service.meta}</small><strong>{service.action}<ArrowRight/></strong></Link></Reveal>)}</div></section>
  <section className="home-process"><div className="wrap"><Reveal><div className="section-heading centered"><div><p className="eyebrow">How Smart RTO works</p><h2>One clear journey from start to finish</h2><p>You always know where you are, what is required and what happens next.</p></div></div></Reveal><ProcessIllustration/><div className="process-grid">{[["01","Choose a service","Start with a plain-language overview and a realistic time estimate."],["02","Complete guided steps","Progressive forms, contextual help and automatic local saving reduce repetition."],["03","Track the next action","A simple timeline shows completed stages and highlights what you need to do."]].map(([n,t,c],i)=><Reveal delay={i*.08} key={n}><article><i>{n}</i><h3>{t}</h3><p>{c}</p>{i<2&&<ArrowRight/>}</article></Reveal>)}</div></div></section>
  <section className="home-section wrap why-grid"><Reveal direction="left"><div className="why-copy"><p className="eyebrow">Designed for first-time users</p><h2>A calmer public-service experience</h2><p>Smart RTO replaces unfamiliar terminology and dense forms with focused steps, readable guidance and predictable feedback.</p><Link className="button secondary" href="/how-it-works">See the citizen guide <ArrowRight/></Link></div></Reveal><Reveal direction="right"><div className="benefit-list">{[[CheckCircle2,"Progress is always visible","Completed, current and upcoming work use words and clear states—not colour alone."],[MapPin,"Helpful local context","Demo RTO suggestions and appointment guidance appear only when relevant."],[ShieldCheck,"Privacy-aware by design","Fictional data stays in your browser and every simulated action is labelled."]].map(([Icon,t,c])=><article key={String(t)}><span><Icon/></span><div><h3>{String(t)}</h3><p>{String(c)}</p></div></article>)}</div></Reveal></section>
  <section className="inclusive-band"><div className="wrap inclusive-grid"><Reveal><div><span className="inclusive-icon"><Languages/></span><p className="eyebrow">Languages</p><h2>Use the portal in the language you understand best.</h2><p>English and ten Indian languages are available from the language control on every page.</p></div></Reveal><Reveal delay={.08}><div><span className="inclusive-icon"><Accessibility/></span><p className="eyebrow">Accessibility</p><h2>Built for keyboards, screen readers and smaller screens.</h2><p>Visible focus, responsive layouts, reduced-motion support and clear labels are part of the system.</p></div></Reveal></div></section>
  <section className="guide-cta wrap"><Reveal><div><p className="eyebrow">Prefer to read first?</p><h2>Follow the Learner Licence guide before you begin.</h2><p>Understand the information, documents and appointment steps in about three minutes.</p><Link className="button primary" href="/how-it-works">Open step-by-step guide <ArrowRight/></Link></div></Reveal></section>
  <section className="prototype-notice wrap"><ShieldCheck/><div><strong>Independent prototype</strong><p>Smart RTO is a fictional demonstration and does not connect to MoRTH, NIC, Parivahan, Sarathi, VAHAN or a State Transport Department.</p></div></section>
 </main><MobileBottomNav/><PrototypeFooter/></>}
