"use client";
import Link from "next/link";
import { ArrowRight, Car, Gavel, Search, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { PageShell } from "./page-shell";

const catalog=[{cat:"Driving licence",items:[{t:"Learner Licence",d:"Complete a guided, resumable demo application.",h:"/apply/learner-licence",live:true},{t:"Driving Licence Services",d:"Guidance for new, renewal and duplicate licences.",h:"/guides/driving-licence"}]},{cat:"Vehicle & records",items:[{t:"Check a vehicle",d:"Search one seeded synthetic registration.",h:"/vehicles",live:true},{t:"Registration guidance",d:"Understand RC services in simple language.",h:"/guides/vehicle-services"}]},{cat:"Visits & support",items:[{t:"Appointments",d:"Book or manage a simulated RTO visit.",h:"/appointments",live:true},{t:"eChallan",d:"Check and pay a fictional demonstration challan.",h:"/challans",live:true},{t:"Grievance",d:"Raise a mock service issue in three steps.",h:"/grievance",live:true}]}];
export function Services(){return <PageShell><section className="page-hero"><div className="content-wrap"><p className="eyebrow">Service catalogue</p><h1>What can we help you with?</h1><p>Start with a working demo journey or read plain-language guidance before you begin.</p></div></section><div className="content-wrap catalogue">{catalog.map(group=><section key={group.cat}><h2>{group.cat}</h2><div className="catalog-grid">{group.items.map(item=><Link href={item.h} className="catalog-card" key={item.t}><span className={item.live?"status-pill":"status-pill guide"}>{item.live?"Working demo":"Guidance only"}</span><h3>{item.t}</h3><p>{item.d}</p><b>Open service <ArrowRight/></b></Link>)}</div></section>)}</div></PageShell>}

export function VehicleCheck(){const [searched,setSearched]=useState(false);return <PageShell><section className="tool-page content-wrap"><div className="tool-intro"><span className="tool-icon"><Car/></span><p className="eyebrow">Synthetic vehicle records</p><h1>Check a demo vehicle</h1><p>Try the seeded registration <strong>MH10AB1234</strong>. No real vehicle database is searched.</p></div><div className="search-card"><label>Vehicle registration number<input defaultValue="MH10AB1234"/></label><button className="button primary" onClick={()=>setSearched(true)}><Search/>Check demo record</button></div>{searched&&<div className="record-card"><div className="record-head"><div><span className="badge">Demo vehicle record</span><h2>Demo Hatchback</h2><p>MH10AB1234 · Petrol</p></div><ShieldCheck/></div><dl className="record-grid"><dt>Owner</dt><dd>A**** K****</dd><dt>Registration validity</dt><dd className="good">Valid</dd><dt>Insurance</dt><dd>Until 10 Dec 2026</dd><dt>PUCC</dt><dd className="warn">Expires 12 Sep 2026</dd><dt>Tax</dt><dd className="good">Paid</dd><dt>Fitness</dt><dd>Not applicable</dd></dl></div>}</section></PageShell>}

export function ChallanCheck(){const [searched,setSearched]=useState(false);const [paid,setPaid]=useState(false);return <PageShell><section className="tool-page content-wrap"><div className="tool-intro"><span className="tool-icon"><Gavel/></span><p className="eyebrow">Demo eChallan</p><h1>Check a fictional challan</h1><p>Try <strong>DEMO-CH-100023</strong>. This prototype never accesses private government records.</p></div><div className="search-card"><label>Vehicle or demo challan number<input defaultValue="DEMO-CH-100023"/></label><button className="button primary" onClick={()=>setSearched(true)}><Search/>Search</button></div>{searched&&<div className="challan-card"><div><span className="badge">Demo / Mock service</span><p>Challan DEMO-CH-100023</p><h2>{paid?"Test payment successful":"Helmet violation — Demo"}</h2><span>20 Aug 2026 · Maharashtra</span></div>{paid?<div className="paid-state"><ShieldCheck/><strong>TESTCH-2026-88421</strong><span>No money was charged.</span></div>:<div className="challan-amount"><span>Pending amount</span><strong>₹500 Demo</strong><button className="button primary" onClick={()=>setPaid(true)}>Pay test challan</button><Link href="/grievance">Raise grievance</Link></div>}</div>}</section></PageShell>}
