"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Car, FileCheck2, FileText, Gauge, Landmark, Search, ShieldAlert, WalletCards } from "lucide-react";
import { Draft, loadApplication, loadDraft } from "@/lib/storage";
import { PageShell } from "./page-shell";

const quick=[{t:"Learner Licence",d:"Start or continue",i:FileText,h:"/apply/learner-licence"},{t:"Book appointment",d:"Choose a demo slot",i:CalendarDays,h:"/appointments"},{t:"Track application",d:"View status",i:Search,h:"/track"},{t:"Check vehicle",d:"Synthetic records",i:Car,h:"/vehicles"},{t:"Check challan",d:"Demo challans",i:ShieldAlert,h:"/challans"},{t:"Document wallet",d:"Demo documents",i:WalletCards,h:"/wallet"}];
export function Dashboard(){const [draft,setDraft]=useState<Draft|null>(null);const [hasApp,setHasApp]=useState(false);useEffect(()=>{const timer=setTimeout(()=>{setDraft(loadDraft());setHasApp(Boolean(loadApplication()))},0);return()=>clearTimeout(timer)},[]);const progress=Math.round(((draft?.step||0)/8)*100);
return <PageShell><section className="dashboard-hero"><div className="content-wrap"><div><p className="eyebrow">Tuesday, 25 August</p><h1>Good afternoon, Demo Citizen</h1><p>What would you like to do today?</p></div><div className="demo-mode-card"><Gauge/><div><strong>Reviewer mode is on</strong><span>All records and services are simulated.</span></div></div></div></section><div className="content-wrap dashboard-layout"><section><div className="panel-heading"><div><span>Continue where you left off</span><h2>{hasApp?"Your submitted application":"Learner Licence application"}</h2></div><span className="status-pill">{hasApp?"Appointment scheduled":"Draft"}</span></div><article className="continue-card"><div className="continue-main"><div className="service-symbol"><Landmark/></div><div><p className="kicker">Learner Licence · Maharashtra</p><h3>{hasApp?"Application submitted":progress?`${progress}% complete`:"Ready to begin"}</h3><p>{hasApp?"Your documents passed the mock check. Your next step is the appointment.":"Your progress is saved automatically on this device."}</p></div></div><div className="continue-action">{!hasApp&&<><div className="progress-track"><span style={{width:`${Math.max(progress,6)}%`}}/></div><span>{Math.max(progress,0)}% complete</span></>}<Link className="button primary" href={hasApp?"/track":"/apply/learner-licence"}>{hasApp?"Track application":"Continue application"}<ArrowRight size={17}/></Link></div></article><div className="section-title"><div><p className="eyebrow">Quick services</p><h2>What do you need help with?</h2></div><Link className="text-link" href="/services">All services</Link></div><div className="quick-grid">{quick.map(({t,d,i:Icon,h})=><Link href={h} className="quick-card" key={t}><Icon/><div><strong>{t}</strong><span>{d}</span></div><ArrowRight className="quick-arrow"/></Link>)}</div></section><aside className="dashboard-aside"><div className="aside-card accent"><div className="aside-title"><CalendarDays/><span>Upcoming appointment</span></div><strong>29 August · 11:20 AM</strong><p>MH-10 Sangli RTO · Demo</p><Link href="/appointments">View appointment →</Link></div><div className="aside-card"><div className="aside-title"><FileCheck2/><span>Your updates</span></div><ul className="update-list"><li><i className="green-dot"/><div><strong>Document check complete</strong><span>Mock verification · Today</span></div></li><li><i className="orange-dot"/><div><strong>PUCC expires soon</strong><span>18 days remaining · Demo</span></div></li></ul></div></aside></div></PageShell>}
