"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { CheckCircle2, LockKeyhole, ShieldCheck, Smartphone } from "lucide-react";
import { setSession } from "@/lib/storage";

export function DemoLogin(){
  const router=useRouter(); const [mobile,setMobile]=useState(""); const [otp,setOtp]=useState(""); const [stage,setStage]=useState<"mobile"|"otp">("mobile"); const [error,setError]=useState("");
  function continueLogin(){if(stage==="mobile"){if(!/^\d{10}$/.test(mobile)){setError("Enter the 10-digit demo mobile number.");return}setError("");setStage("otp");return}if(otp!=="123456"){setError("That demo OTP is not correct. Use 123456.");return}setSession();router.push("/dashboard")}
  function fillDemo(){setMobile("9999999999");setOtp("123456");setError("");setStage("otp")}
  return <PageShell><section className="auth-page"><div className="auth-intro"><span className="auth-icon"><ShieldCheck/></span><p className="eyebrow">Secure demo sign in</p><h1>Welcome back</h1><p>Sign in to continue an application, see appointments and check what happens next.</p><ul><li><CheckCircle2/> No real OTP is sent</li><li><CheckCircle2/> No government identity is checked</li><li><CheckCircle2/> Your draft stays on this device</li></ul></div><div className="auth-card"><span className="badge">Demo / Mock service</span><h2>{stage==="mobile"?"Sign in with mobile":"Enter demo OTP"}</h2><p>{stage==="mobile"?"Use the reviewer account below or any fictional 10-digit number.":`Demo OTP sent to ${mobile}. No SMS was sent.`}</p>{stage==="mobile"?<label>Mobile number <span>Required</span><div className="input-with-icon"><Smartphone/><input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" placeholder="9999999999" autoFocus/></div></label>:<label>6-digit demo OTP <span>Required</span><div className="input-with-icon"><LockKeyhole/><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" placeholder="123456" autoFocus/></div><small className="help-text">Mock OTP: <strong>123456</strong></small></label>}{error&&<p className="field-error" role="alert">{error}</p>}<button className="button primary full" onClick={continueLogin}>{stage==="mobile"?"Continue":"Sign in to demo"}</button><button className="demo-fill" onClick={fillDemo}>Fill demo login</button><div className="demo-credentials"><strong>Reviewer access</strong><span>Mobile: 9999999999</span><span>OTP: 123456</span></div><p className="auth-disclaimer">Smart RTO is an independent hackathon prototype, not a government service.</p></div></section></PageShell>
}
import { PageShell } from "./page-shell";
