"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarDays, Check, CheckCircle2, Circle, Download, FileCheck2, Printer, Search } from "lucide-react";
import { DemoApplication, loadApplication } from "@/lib/storage";
import { PageShell } from "./page-shell";

export function Tracking(){const [app,setApp]=useState<DemoApplication|null>(null);const [query,setQuery]=useState("");useEffect(()=>{const timer=setTimeout(()=>setApp(loadApplication()),0);return()=>clearTimeout(timer)},[]);const shown=app||{id:"SRTO-LL-2026-001284",status:"appointment-scheduled",appointment:"29 Aug · 11:20 AM",rto:"MH-10 Sangli RTO",submittedAt:"2026-08-25",fullName:"Demo Citizen"};
return <PageShell><section className="page-hero compact-hero"><div className="content-wrap"><p className="eyebrow">Application status</p><h1>Track your progress</h1><p>See what is complete, what happens next and whether you need to act.</p><div className="track-search"><Search/><input aria-label="Application number" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Enter demo application number"/><button className="button primary">Track</button></div></div></section><div className="content-wrap tracking-layout"><section><div className="application-summary"><div><span className="status-pill">Appointment scheduled</span><p>Learner Licence · Demo</p><h2>{query||shown.id}</h2><span>Last updated 25 Aug 2026, 3:21 PM</span></div><div><button aria-label="Print acknowledgement"><Printer/></button><button aria-label="Download acknowledgement"><Download/></button></div></div><div className="next-action"><CalendarDays/><div><span>Your next action</span><strong>Attend the simulated learner test appointment</strong><p>29 August 2026 · 11:20 AM · {shown.rto}</p></div><Link href="/appointments">View appointment</Link></div><article className="timeline-card"><h2>Application timeline</h2><p>Every status below is simulated for this hackathon prototype.</p><ol className="timeline">{[["Application submitted","25 Aug 2026","Your test payment and application were received."],["Documents checked","25 Aug 2026","Your synthetic documents passed the mock verification."],["Appointment scheduled","29 Aug 2026","Attend the demo learner test at the selected time."],["Learner test","Pending","This step will update after the simulated appointment."],["Approval","Pending","Final decision will be shown here."],["Licence available","Pending","A demo licence will appear in your wallet."]].map(([t,d,c],i)=><li className={i<2?"done":i===2?"active":""} key={t}><i>{i<2?<Check/>:i===2?<CalendarDays/>:<Circle/>}</i><div><strong>{t}</strong><span>{d}</span><p>{c}</p></div></li>)}</ol></article></section><aside className="tracking-aside"><div className="aside-card"><div className="aside-title"><FileCheck2/><span>Application details</span></div><dl><dt>Applicant</dt><dd>{shown.fullName}</dd><dt>Service</dt><dd>Learner Licence</dd><dt>RTO</dt><dd>{shown.rto}</dd><dt>Appointment</dt><dd>{shown.appointment}</dd><dt>Payment</dt><dd>TESTPAY-2026-483921</dd></dl></div><div className="aside-card mock-doc"><CheckCircle2/><strong>Acknowledgement ready</strong><p>Includes a large DEMO watermark and no sensitive identity data.</p><button className="button secondary full" onClick={()=>window.print()}><Download/>Print demo copy</button></div></aside></div></PageShell>}
